//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGUI.App_Data
{
    using System;

    public partial class CartLine
    {
        public int CartLineID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public int Quantity { get; set; }

        public virtual Order Order { get; set; }
        public Product _Product { get; set; }
        public virtual Product Product { get; set; }
    }
}
