//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGUI.App_Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ClupStoreEntities : DbContext
    {
        public ClupStoreEntities()
            : base("name=ClupStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<CartLine> CartLines { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Product> Products { get; set; }
    
        public virtual ObjectResult<Report_Financials_Result> Report_Financials()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Report_Financials_Result>("Report_Financials");
        }
    
        public virtual ObjectResult<Report_Products_Result> Report_Products()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Report_Products_Result>("Report_Products");
        }
    
        public virtual ObjectResult<Report_Users_Result> Report_Users()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Report_Users_Result>("Report_Users");
        }
    }
}
